import { corsJson, corsPreflight } from "../_lib/cors"
import { randomItem } from "../_lib/random"

const replies = [
  "Definitely! 8-0 shot!",
  "You lookin' badass!",
  "Signs pointin' to DAMN STRAIGHT!",
  "HELL YEA!",
  "Shit yea fam!",
  "SHIT NO.... ok ok yea.",
  "ESKETIT!!!",
  "OK Homie! Let's do it!",
  "Shit dogg, I'm busy... but yea.",
  "LETS GOOOOOOOO!",
  "My homie's sayin nah.",
  "Real damn doubtful...",
  "Yo ass be butta!",
  "Get yo little ass outta here with that shit!",
  "Fuck no! Fo real!? smh",
  "I say goddamm!",
  "I'm hungover... Hit me up later.",
  "I aint tellin yo ass now, BITCH!",
  "Gotta throw salt in yo game, bro",
  "Hold on, gotta hit this bong",
  "BRUH!!",
]
const replies2 = [
  "Roll for satisfaction.",
  "Your charisma modifier says yes.",
  "Natural 1. Not tonight, adventurer.",
  "The dice are feeling frisky.",
  "Ask again after a long rest.",
  "A crit fail in the bedroom, my friend.",
  "It’s super effective… wrong game, but still hot.",
  "Your future’s looking thicc with two c’s.",
  "The gods are watching. And they like it.",
  "A steamy encounter is imminent.",
  "You’ve angered the DM. Expect punishment.",
  "Your saving throw against temptation fails.",
  "Critical hit—right in the feels.",
  "You’re about to multiclass into chaos.",
  "That’s a natural 20 on flirtation.",
  "You’re proficient in bad decisions.",
  "The potion’s kicking in. Proceed with caution.",
  "Roll initiative. Things are heating up.",
  "You sense… heavy petting.",
  "Your armor class won’t save you from this one.",
  "Advantage on seduction checks.",
  "The tavern wench approves.",
  "Something’s brewing—and it’s not ale.",
  "You hear moaning in the dungeon. Again.",
  "That’s not a wand—it’s a focus.",
  "A soft 16. Could go either way.",
  "Fate wants to take a short rest… with you.",
  "You’ve triggered a trap of passion.",
  "Your dice are trembling.",
  "A mysterious hand slides your way.",
  "The stars align for mischief.",
  "It’s not a mimic. Probably.",
  "You roll a 69. Nice.",
  "Someone’s about to fail their concentration check.",
  "Prepare for a skill challenge in stamina.",
  "Your bedroll awaits you.",
  "You hear, 'Oh my gods, yes!' from the next room.",
  "Your initiative is impressive.",
  "Your charisma check succeeds—barely.",
  "It’s a critical fumble. On your pants.",
  "Something wicked—and hot—this way comes.",
  "You’re under the effect of charm person.",
  "That’s a risky roll, hero.",
  "Your spell slot’s spent. Take a nap.",
  "The dungeon master smirks knowingly.",
  "Your familiar is blushing.",
  "A wandering bard joins the fun.",
  "You rolled disadvantage on rhythm.",
  "A little inspiration never hurt anyone.",
  "You found a new use for mage hand.",
  "You cast entangle. It gets messy.",
  "You feel your constitution tested.",
  "The dice whisper… 'do it.'",
  "You roll a 20 for foreplay.",
  "Critical success. The room applauds.",
  "The gods approve of your debauchery.",
  "That’s what she crit.",
  "Your initiative rises… dramatically.",
  "You’re about to gain XP in questionable ways.",
  "You sense a strong aura of desire.",
  "Your hit points increase temporarily.",
  "The bard says, 'I’d sing about that.'",
  "Someone’s casting heat metal on your armor.",
  "You feel inspiration… in your loins.",
  "Your passive perception sees too much.",
  "The rogue steals your heart. And your pants.",
  "That’s not thunderwave—that’s passion.",
  "Your luck score is… provocative.",
  "The dragon’s not the only thing with a hoard.",
  "You’re entering difficult terrain.",
  "The dice want you to get lucky.",
  "Someone’s about to roll a new character… nine months later.",
  "That’s a spell slot you’ll remember.",
  "You critically hit on charm.",
  "Your constitution saving throw fails.",
  "Your next encounter involves soft lighting.",
  "A natural 20 and a satisfied grin.",
  "The DM says, 'Describe it in detail.'",
  "You gain the 'afterglow' condition.",
  "That wand’s got a bit of extra charge.",
  "The tavern goes silent… then cheers.",
  "You failed your wisdom save. Again.",
  "Your armor class won’t protect you from this heat.",
  "A steamy subplot unfolds.",
  "You sense a chaotic energy in the room.",
  "You’re about to discover the true meaning of polymorph.",
  "Someone rolled for initiative. Twice.",
  "A short rest becomes a long rest.",
  "The dice are winking at you.",
  "You’ve got advantage on pillow talk.",
  "The bard’s lute plays something… suggestive.",
  "You find a scroll labeled 'safe word.'",
  "Your endurance check will be tested.",
  "That’s a failed stealth check—you’ve been caught.",
  "You feel inspired. Inappropriately.",
  "The potion of lust takes effect.",
  "You gain temporary hit points and satisfaction.",
  "A sultry NPC appears. Roll for composure.",
  "Your spell fizzles… but your sparks fly.",
  "That’s not a cursed item—it’s just misunderstood.",
  "You crit fail to resist temptation.",
  "You gain the 'flustered' condition.",
  "Someone’s casting suggestion. You like it.",
  "You rolled a dirty 20.",
  "You gain +2 to flirting for the next hour.",
  "The dice say yes… enthusiastically.",
  "You’re about to unlock an achievement: 'Hot Mess.'",
  "Your bardic inspiration is… impressive.",
  "A gentle breeze lifts more than spirits.",
  "That’s a dexterity check you’ll never forget.",
  "Your encounter table got spicy.",
  "You rolled initiative and lost your clothes.",
  "That’s a spell of pure chaos. Delicious.",
  "You hear 'oohs' from the tavern crowd.",
  "You gain the 'smug satisfaction' buff.",
  "A new quest appears: 'The Morning After.'",
  "You roll for stealth—and fail gloriously.",
  "Someone’s about to roll a persuasion check in bed.",
  "That’s a crit success in stamina.",
  "You find yourself in the 'forbidden section' of the spellbook.",
  "You rolled a 'maybe later' with heavy breathing.",
  "The dice wink. You wink back.",
  "Your roll? Hotter than a fireball."
]

export const runtime = "nodejs"

export const OPTIONS = () => corsPreflight()

export const GET = () => corsJson({ message: randomItem(replies2) })
